apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cors-for-testing
spec:
  hosts:
  - "*"
  gateways:
  - my-gateway
  http:
  - route:
    - destination:
        host: hello-backend
        port:
          number: 50066
    corsPolicy:
      allowOrigin:
      - "*"
      allowMethods:
      - POST
      - GET
      - OPTIONS
      - DELETE
      - PUT
      allowHeaders:
      - keep-alive
      - user-agent
      - cache-control
      - content-type
      - content-transfer-encoding
      - x-accept-content-transfer-encoding
      - x-accept-response-streaming
      - x-user-agent
      - x-grpc-web
      - grpc-timeout
      exposeHeaders:
      - grpc-status
      - grpc-message
      allowCredentials: true
  # - match:
  #   - port: 80
  #   route:
  #   - destination:
  #       host: hello-backend
  #       port:
  #         number: 3000
