apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ include "grpc-web-hello.fullname" . }}-backend"
  labels:
    app.kubernetes.io/name: {{ include "grpc-web-hello.name" . }}
    helm.sh/chart: {{ include "grpc-web-hello.chart" . }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "grpc-web-hello.name" . }}
      app.kubernetes.io/component: backend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "grpc-web-hello.name" . }}
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: "{{ include "grpc-web-hello.fullname" . }}-backend"
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          imagePullPolicy: {{ .Values.backend.pullPolicy }}
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
            - containerPort: 50066
              name: grpc-web-port
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /backend-health
              port: http
          readinessProbe:
            httpGet:
              path: /backend-health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

---
apiVersion: v1
kind: Service

metadata:
  name: "{{ include "grpc-web-hello.fullname" . }}-backend"
  labels:
    app.kubernetes.io/name: {{ include "grpc-web-hello.name" . }}
    helm.sh/chart: {{ include "grpc-web-hello.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: backend

spec:
  ports:
  - name: grpc-web-port
    port: 50066
    protocol: TCP
    targetPort: 50066
  - name: http-port
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/name: {{ include "grpc-web-hello.name" . }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
