apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: "{{ include "grpc-web-hello.fullname" . }}-frontend"
  labels:
    app.kubernetes.io/name: {{ include "grpc-web-hello.name" . }}
    helm.sh/chart: {{ include "grpc-web-hello.chart" . }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "grpc-web-hello.name" . }}
      helm.sh/chart: {{ include "grpc-web-hello.chart" . }}
      app.kubernetes.io/component: frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "grpc-web-hello.name" . }}
        helm.sh/chart: {{ include "grpc-web-hello.chart" . }}
        app.kubernetes.io/component: frontend
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
        - name: "{{ include "grpc-web-hello.fullname" . }}-frontend"
          image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
          imagePullPolicy: {{ .Values.frontend.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "grpc-web-hello.fullname" . }}-frontend"
  labels:
    app.kubernetes.io/name: {{ include "grpc-web-hello.name" . }}
    helm.sh/chart: {{ include "grpc-web-hello.chart" . }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "grpc-web-hello.name" . }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
