apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: hello-frontend
  name: hello-frontend

spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-frontend
    spec:
      containers:
      - image: hello-grpc-client
        imagePullPolicy: Never
        name: hello-frontend
        ports:
        - containerPort: 8080
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello-frontend
  name: hello-frontend

spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-frontend
